### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by imlimws** [berinhard/pyp5js#190]
After followed all the instruction for installation, I succeeded to get to the browser [ http://127.0.0.1:5000/ ] and created a Sketch. 
But when I click [ Click here ] to see the result, I get the Error as below.
I am using the Window based computer under Korean environment.

Please give me a advice to solve this problem. I really like to use Pyp5js.
------------------------------------
127.0.0.1 - - [29/Oct/2021 10:55:30] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2021 10:55:30] "GET /static/styles/custom.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Oct/2021 10:55:30] "GET /static/styles/basscss-7.1.1.min.css HTTP/1.1" 304 -
127.0.0.1 - - [29/Oct/2021 10:55:30] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [29/Oct/2021 10:55:32] "GET /new-sketch/ HTTP/1.1" 200 -
127.0.0.1 - - [29/Oct/2021 10:55:36] "POST /new-sketch/ HTTP/1.1" 200 -
[2021-10-29 10:55:38,501] ERROR in app: Exception on /sketch/aaa/ [GET]
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\pyp5js\http\web_app.py", line 90, in render_sketch_view
    commands.compile_sketch(sketch_name)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\pyp5js\commands.py", line 62, in compile_sketch
    compile_sketch_js(sketch)
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\pyp5js\compiler.py", line 92, in compile_sketch_js
    compiler.compile_sketch_js()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\pyp5js\compiler.py", line 22, in compile_sketch_js
    self.prepare()
  File "c:\users\administrator\appdata\local\programs\python\python37-32\lib\site-packages\pyp5js\compiler.py", line 39, in prepare
    fd.write(content)
UnicodeEncodeError: 'cp949' codec can't encode character '\xd3' in position 24972: illegal multibyte sequence
127.0.0.1 - - [29/Oct/2021 10:55:38] "GET /sketch/aaa/ HTTP/1.1" 500 -

**Comment by berinhard** [comment]
Thanks for reporting this issue @imlimws! 

Probably the error is happening due to encoding errors. For the traceback, it seems you're using `cp949` coded and this can be causing the issue.

To fix this, I'll probably have to explicitly force all open/close operations on files such as the sketch itself to explicitly set `utf-8` instead of using system's default encoding. This can be a reference:

```python
with codecs.open("test_output", "w", "utf-8-sig") as temp:
    temp.write("hi mom\n")
    temp.write(u"This has ♭")
```

**Comment by berinhard** [comment]
If anyone wants to help with, here's how to reproduce it: 

Replace [line 38 at compiller.py](https://github.com/berinhard/pyp5js/blob/develop/pyp5js/compiler.py#L38) by this:

```python
with self.sketch.target_sketch.open('w', encoding="cp949") as fd:
    fd.write(content)
```
