### ISSUE TITLE
Monitor command is not working when running from the sketch dir

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#44]
The transcrypt command is working:

```
(sandbox) [bernardo@macalandia ~/envs/sandbox]$ pyp5js transcrypt my_sketch
Converting Python to P5.js...
Running command:
	 transcrypt -xp /home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/pyp5js -b -m -n my_sketch/my_sketch.py

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.7.12
Copyright (C) Geatec Engineering. License: Apache 2.0


Saving target code in: /home/bernardo/envs/sandbox/my_sketch/__target__/org.transcrypt.__runtime__.js
Saving target code in: /home/bernardo/envs/sandbox/my_sketch/__target__/pyp5js.js
Saving target code in: /home/bernardo/envs/sandbox/my_sketch/__target__/my_sketch.js

Ready

Your sketch is ready and available at my_sketch/index.html
(sandbox) [bernardo@macalandia ~/envs/sandbox]$ cd my_sketch/
(sandbox) [bernardo@macalandia ~/envs/sandbox/my_sketch]$ pyp5js transcrypt my_sketch
Converting Python to P5.js...
Running command:
	 transcrypt -xp /home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/pyp5js -b -m -n /home/bernardo/envs/sandbox/my_sketch/my_sketch.py

Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.7.12
Copyright (C) Geatec Engineering. License: Apache 2.0


Saving target code in: /home/bernardo/envs/sandbox/my_sketch/__target__/org.transcrypt.__runtime__.js
Saving target code in: /home/bernardo/envs/sandbox/my_sketch/__target__/pyp5js.js
Saving target code in: /home/bernardo/envs/sandbox/my_sketch/__target__/my_sketch.js

Ready

Your sketch is ready and available at /home/bernardo/envs/sandbox/my_sketch/index.html
```

But the `monitor` isn't:

```
(sandbox) [bernardo@macalandia ~/envs/sandbox]$ pyp5js monitor my_sketch
Monitoring for changes in /home/bernardo/envs/sandbox/my_sketch...
^CExiting monitor...
(sandbox) [bernardo@macalandia ~/envs/sandbox]$ cd my_sketch/
(sandbox) [bernardo@macalandia ~/envs/sandbox/my_sketch]$ pyp5js monitor my_sketch
Monitoring for changes in /home/bernardo/envs/sandbox/my_sketch/my_sketch...
Traceback (most recent call last):
  File "/home/bernardo/.virtualenvs/sandbox/bin/pyp5js", line 10, in <module>
    sys.exit(command_line_entrypoint())
  File "/home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/pyp5js/cli.py", line 78, in monitor_sketch
    commands.monitor_sketch(sketch_name, sketch_dir)
  File "/home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/pyp5js/commands.py", line 102, in monitor_sketch
    observer.start()
  File "/home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/watchdog/observers/api.py", line 255, in start
    emitter.start()
  File "/home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/watchdog/utils/__init__.py", line 110, in start
    self.on_thread_start()
  File "/home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 199, in __init__
    self._add_dir_watch(path, recursive, event_mask)
  File "/home/bernardo/.virtualenvs/sandbox/lib/python3.6/site-packages/watchdog/observers/inotify_c.py", line 379, in _add_dir_watch
    raise OSError('Path is not a directory')
OSError: Path is not a directory
```

**Comment by villares** [comment]
@berinhard I guess this is the wrong place to make a feature request... but... could the `new` command have a `-m` or `--monitor` flag?
