### ISSUE TITLE
Error with new minified files

### ISSUE THREAD

**Issue by berinhard** [berinhard/pyp5js#57]
Traceback:

```
Traceback (most recent call last):
  File "/home/bernardo/.virtualenvs/sketches/bin/pyp5js", line 10, in <module>
    sys.exit(command_line_entrypoint())
  File "/home/bernardo/.virtualenvs/sketches/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/bernardo/.virtualenvs/sketches/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/bernardo/.virtualenvs/sketches/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bernardo/.virtualenvs/sketches/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bernardo/.virtualenvs/sketches/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/bernardo/.virtualenvs/sketches/lib/python3.6/site-packages/pyp5js/cli.py", line 32, in configure_new_sketch
    sketch_py, index_html = commands.new_sketch(sketch_name, sketch_dir)
  File "/home/bernardo/.virtualenvs/sketches/lib/python3.6/site-packages/pyp5js/commands.py", line 41, in new_sketch
    shutil.copyfile(src, dest)
  File "/home/bernardo/.virtualenvs/sketches/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: Path('/home/bernardo/.virtualenvs/sketches/lib/python3.6/site-packages/pyp5js/static/p5/p5.min.js')
```

**Comment by berinhard** [comment]
Current `setup.py` implementation with `package_data` only works for `bdist`, not for `sdist`. There's more about this classic little Python's packaging issue in this [Stackoverflow answer](https://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distribute#comment21443047_14159430). We have to add `MANIFEST.in` to support `sdist` as well, as described in [the docs](https://docs.python.org/3/distutils/sourcedist.html#manifest-template).
