### ISSUE TITLE
Advice on installing pyp5js

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#58]
I need advice on installing it again.

Should I have tried `sudo pip3 install`? I haven't because I had a bad experience beforem so I tried using `--user` as suggested by the first try... Then it looked like it was installed, then, it didn't work.

Please assume I have no idea of what I'm doing in the command line.

```
Installing collected packages: pyp5js
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/pyp5js'
Consider using the `--user` option or check the permissions.

villares@VPCEE25FX:~$ pip3 install pyp5js --user
Collecting pyp5js
  Using cached https://files.pythonhosted.org/packages/de/06/7b87cfb61ccf6227fa57c07903a4f3a8291c0a105a26fe6a8a922aff74b0/pyp5js-0.1.0-py3-none-any.whl
Requirement already satisfied: Jinja2==2.10.1 in ./.local/lib/python3.6/site-packages (from pyp5js) (2.10.1)
Requirement already satisfied: PyYAML==5.1 in ./.local/lib/python3.6/site-packages (from pyp5js) (5.1)
Requirement already satisfied: Unipath==1.1 in ./.local/lib/python3.6/site-packages (from pyp5js) (1.1)
Requirement already satisfied: cprint==1.1 in ./.local/lib/python3.6/site-packages (from pyp5js) (1.1)
Requirement already satisfied: watchdog==0.9.0 in ./.local/lib/python3.6/site-packages (from pyp5js) (0.9.0)
Requirement already satisfied: Transcrypt==3.7.12 in ./.local/lib/python3.6/site-packages (from pyp5js) (3.7.12)
Requirement already satisfied: Click==7.0 in ./.local/lib/python3.6/site-packages (from pyp5js) (7.0)
Requirement already satisfied: MarkupSafe>=0.23 in ./.local/lib/python3.6/site-packages (from Jinja2==2.10.1->pyp5js) (1.1.1)
Requirement already satisfied: pathtools>=0.1.1 in ./.local/lib/python3.6/site-packages (from watchdog==0.9.0->pyp5js) (0.1.2)
Requirement already satisfied: argh>=0.24.1 in ./.local/lib/python3.6/site-packages (from watchdog==0.9.0->pyp5js) (0.26.2)
Requirement already satisfied: mypy in ./.local/lib/python3.6/site-packages (from Transcrypt==3.7.12->pyp5js) (0.701)
Requirement already satisfied: typed-ast<1.4.0,>=1.3.1 in ./.local/lib/python3.6/site-packages (from mypy->Transcrypt==3.7.12->pyp5js) (1.3.5)
Requirement already satisfied: mypy-extensions<0.5.0,>=0.4.0 in ./.local/lib/python3.6/site-packages (from mypy->Transcrypt==3.7.12->pyp5js) (0.4.1)
Installing collected packages: pyp5js
Successfully installed pyp5js-0.1.0
villares@VPCEE25FX:~$ cd sketchbook/
villares@VPCEE25FX:~/sketchbook$ pyp5js
Usage: pyp5js [OPTIONS] COMMAND [ARGS]...

  Function to define the entry point for the command line

Options:
  --help  Show this message and exit.

Commands:
  monitor     Command to generate keep watching a sketch's dir and, after...
  new         Create dir and configure boilerplate Params: - sketch_name:...
  transcrypt  Command to generate the P5.js code for a python sketch
              Params:...
villares@VPCEE25FX:~/sketchbook$ pyp5js new test_args
Traceback (most recent call last):
  File "/home/villares/.local/bin/pyp5js", line 10, in <module>
    sys.exit(command_line_entrypoint())
  File "/home/villares/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/villares/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/villares/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/villares/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/villares/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/villares/.local/lib/python3.6/site-packages/pyp5js/cli.py", line 32, in configure_new_sketch
    sketch_py, index_html = commands.new_sketch(sketch_name, sketch_dir)
  File "/home/villares/.local/lib/python3.6/site-packages/pyp5js/commands.py", line 41, in new_sketch
    shutil.copyfile(src, dest)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: Path('/home/villares/.local/lib/python3.6/site-packages/pyp5js/static/p5/p5.min.js')

```

**Comment by villares** [comment]
Same as issue #57
