### ISSUE TITLE
something went wrong serving sketches on macOS

### ISSUE THREAD

**Issue by villares** [berinhard/pyp5js#87]
I was creating a sketch with the new marvelous `pyp5js serve` service on Mac OS and got `Internal Server Error` in the browser when reaching for the sketch.

Maybe this message from the terminal can help shed light:
```
[2019-10-06 21:54:12,326] ERROR in app: Exception on /sketch/oi/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/pyp5js/http/web_app.py", line 64, in render_sketch_view
    commands.transcrypt_sketch(sketch_name)
  File "/usr/local/lib/python3.7/site-packages/pyp5js/commands.py", line 56, in transcrypt_sketch
    compile_sketch_js(sketch_files)
  File "/usr/local/lib/python3.7/site-packages/pyp5js/compiler.py", line 69, in compile_sketch_js
    compiler.compile_sketch_js()
  File "/usr/local/lib/python3.7/site-packages/pyp5js/compiler.py", line 16, in compile_sketch_js
    self.run_compiler()
  File "/usr/local/lib/python3.7/site-packages/pyp5js/compiler.py", line 43, in run_compiler
    proc = subprocess.Popen(shlex.split(command))
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'transcrypt': 'transcrypt'
127.0.0.1 - - [06/Oct/2019 21:54:12] "GET /sketch/oi/ HTTP/1.1" 500 -

```

**Comment by berinhard** [comment]
@villares Hm, it seems that the `subprocess` call is not using the regular `python3.7` context. Take a look on how it changes to this `/usr/local/Cellar/` instead of using your `/usr/local/lib/python3.7/` path:

```
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
```

I'll try to get a MacOS with a few friends to test it out and check what's happening...

**Comment by turicas** [comment]
I'm not sure how easy is to use transcrypt as a library, but we could execute all steps its command-line interface does by transcrypt's `__main__.py` implementation, like in:

```python
import transcrypt.__main__  
# the first import will insert a new path on `sys.path` so we can execute the next one:
from org.transcrypt import compiler

compiler.Program(...)                                                                                        
```

**Comment by berinhard** [comment]
@villares I've tested the lib under 2 different versions of MacOS and it worked properly =/

I'm closing this issue because I've created #89 that should fix this problem as well.
